/* Autogenerated by png2wx.pl on Sat Jan 21 18:57:33 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_trackpoint_pi;
extern wxBitmap *_img_trackpoint_settings;

#endif /* ICONS_H */
